project:
  type: website
  output-dir: docs

website:
  title: "Matias Parra"
  navbar:
    title: false
    left: []
    right:
      - href: trayectoria.qmd
        text: Trayectoria
      - href: blog.qmd
        text: Blog
      - href: https://github.com/miparrar
        text: GitHub
  page-footer:
    center: "Construido con ❤️, 🧉 y 🤖"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
